on:
  workflow_call:
    inputs:
      name:
        required: true
        type: string
      sh:
        required: false
        type: string
        default: "true"
      suffix:
        required: false
        type: string
        default: ""

jobs:

  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        platform: [amd64,arm64]

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up QEMU
        if: matrix.platform == 'arm64'
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_TOKEN }}
      - name: Docker Meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ${{secrets.DOCKER_ORG}}/${{inputs.name}}${{inputs.suffix}}
          flavor: latest=false
          tags: |
            type=raw,value={{date 'YYYYMMDD'}}
            type=raw,value=latest
      - name: Prepare Shell Script
        run: |
          cd ${{inputs.name}}
          bash -c "${{inputs.sh}}"
      - name: Build & Push
        uses: docker/build-push-action@v4
        with:
          context: ${{inputs.name}}
          platforms: linux/${{ matrix.platform }}
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

