name: nginx

on:
  workflow_dispatch:
  push:
    branches: [ main ]
    paths:
      - 'nginx/**'
      - '.github/workflows/nginx.yml'
  schedule:
    - cron: '1 1 1 */3 *'

jobs:
  build:
    uses: ./.github/workflows/docker.yml
    with:
      name: nginx
    secrets: inherit
